import subprocess
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")
subprocess.Popen("./cliente")