import os
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")
os.system("./cliente")